FROM docker.1ms.run/library/node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM docker.1ms.run/library/nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/mypj-frontend/browser /usr/share/nginx/html

EXPOSE 80
