package com.deepvision.studio.forward;

import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.Instant;

public final class ForwardRecordDtos {
  /** 工具类不需要实例化，DTO 只通过内部 record 类型承载请求和响应。 */
  private ForwardRecordDtos() {}

  @Schema(description = "Request body for saving a Mode A forward-pass snapshot")
  /** 保存记录请求：前端提交列表元数据、输入预览图和可完整恢复 A 模式的 snapshot。 */
  public record SaveForwardRecordRequest(
      @Schema(description = "User-visible record name", example = "Edge kernel experiment")
      @NotBlank(message = "Record name is required.")
      @Size(max = 120, message = "Record name must be at most 120 characters.")
      String name,
      @Schema(description = "Selected network template id", example = "cnn-classic")
      @NotBlank(message = "Template id is required.")
      String templateId,
      @Schema(description = "Dataset or sample collection name", example = "Animal")
      @NotBlank(message = "Dataset name is required.")
      String datasetName,
      @Schema(description = "Number of layers in the saved graph", example = "6")
      int layerCount,
      @Schema(description = "Parameter count shown by the frontend", example = "18432")
      long parameterCount,
      @Schema(description = "Optional preview image Data URL generated by the frontend")
      String previewImageDataUrl,
      @Schema(description = "Full frontend snapshot used to restore Mode A state")
      @NotNull(message = "Snapshot is required.")
      JsonNode snapshot
  ) {}

  @Schema(description = "Summary item for a saved Mode A record")
  /** 历史记录列表项，只包含名称、模板、数据集、层数、参数量和预览图路径。 */
  public record ForwardRecordSummary(
      Long id,
      String name,
      String templateId,
      String datasetName,
      int layerCount,
      long parameterCount,
      String imagePath,
      Instant createdAt
  ) {
    /** 从实体生成列表摘要，不读取大字段 snapshotJson，避免列表接口返回过重。 */
    static ForwardRecordSummary from(ForwardRecord record) {
      return new ForwardRecordSummary(
          record.getId(),
          record.getName(),
          record.getTemplateId(),
          record.getDatasetName(),
          record.getLayerCount(),
          record.getParameterCount(),
          record.getImagePath(),
          record.getCreatedAt()
      );
    }
  }

  @Schema(description = "Detail payload for a saved Mode A record")
  /** 历史记录详情，比摘要多出 snapshot，前端用它恢复完整 A 模式页面状态。 */
  public record ForwardRecordDetail(
      Long id,
      String name,
      String templateId,
      String datasetName,
      int layerCount,
      long parameterCount,
      String imagePath,
      Instant createdAt,
      JsonNode snapshot
  ) {
    /** 从实体和已解析的 snapshot 组装详情响应。 */
    static ForwardRecordDetail from(ForwardRecord record, JsonNode snapshot) {
      return new ForwardRecordDetail(
          record.getId(),
          record.getName(),
          record.getTemplateId(),
          record.getDatasetName(),
          record.getLayerCount(),
          record.getParameterCount(),
          record.getImagePath(),
          record.getCreatedAt(),
          snapshot
      );
    }
  }
}
